name: Merge into main branch

on:
  push:
    branches: [ master ]

jobs:
  prepare:
    name: Preparations
    runs-on: ubuntu-20.04

    outputs:
      new_release: ${{ steps.semantic.outputs.new_release_published }}
      release: ${{ steps.semantic.outputs.new_release_version }}
      release_notes: ${{ steps.semantic.outputs.new_release_notes }}

    steps:
    - uses: actions/checkout@v2
      with:
        token: ${{ secrets.ACCESS_TOKEN }}

    - uses: cycjimmy/semantic-release-action@v2
      id: semantic
      env:
        GITHUB_TOKEN: ${{ secrets.ACCESS_TOKEN }}
      with:
        dry_run: true

    - name: Create Release branch
      if: steps.semantic.outputs.new_release_published == 'true'
      env:
        VERSION: ${{ steps.semantic.outputs.new_release_version }}
      run: |
        git config user.email "azory@ydata.ai"
        git config user.name "Azory YData Bot"
        git checkout -b release/$VERSION
        echo $VERSION > VERSION
        git add -f VERSION
        git commit -a -m "chore(version): [CI] populate version file with $VERSION"
        git push origin release/$VERSION

  prerelease:
    if: needs.prepare.outputs.new_release == 'true'

    name: Create Pre-Release
    runs-on: ubuntu-20.04

    needs: prepare

    steps:
    - name: Create Release
      uses: actions/create-release@v1
      env:
        GITHUB_TOKEN: ${{ secrets.ACCESS_TOKEN }}
        VERSION: ${{ needs.prepare.outputs.release }}
      with:
        commitish: release/${{ env.VERSION }}
        tag_name: ${{ env.VERSION }}
        release_name: ${{ env.VERSION }}
        body: ${{ needs.prepare.outputs.release_notes }}
        draft: false
        prerelease: true

